#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re



def textname(name):
#1
    file_object=open('E:\\{}.txt'.format(name),'rt',encoding='utf-8')
    lines_seen = set()
    s=file_object.readlines()
    file_object.flush()
    file_object.close()

    for line in s:
        if '、' in line:# and ':' and '；'
            pass
        else:
            text_1 = open('E:\\{}-去掉顿号.txt'.format(name), 'a',encoding='utf-8')
            text_1.write(line)
            lines_seen.add(line)
            print(line)


# 2
    file_object=open('E:\\{}-去掉顿号.txt'.format(name),'rt',encoding='utf-8')
    a = re.findall('(“[\w].*?”)', file_object.read())#[\u4e00-\u9fa5a-zA-Z0-9\“]（）<>+=\'"
    # a = re.findall('[^\、][\u4e00-\u9fa5a-zA-Z0-9]*', file_object.read())
    lines_seen = set()
    print(a)
    for line in a:
        if line not in lines_seen:
            text_1 = open('E:\\{}-限制字数.txt'.format(name), 'a',encoding='utf-8')
            text_1.write(line + '\n')
            lines_seen.add(line)
            print(line)
    file_object.close()



#3
    file_object=open('E:\\{}-限制字数.txt'.format(name),'rt',encoding='utf-8')
    a = re.findall('(?<=，)[\u4e00-\u9fa5]{15,36}(?=。)|(?<=，)[\u4e00-\u9fa5]{15,36}(?=,)', file_object.read())#[\u4e00-\u9fa5a-zA-Z0-9\“]（）<>+=\'"
    lines_seen = set()
    print(a)
    for line in a:
        if line not in lines_seen:
        #if len(line) >= 16 and len(line) <= 36 and line not in lines_seen:
            text_1 = open('E:\\{}-正则匹配.txt'.format(name), 'a',encoding='utf-8')
            text_1.write(line + '\n')
            lines_seen.add(line)
            print(line)
    file_object.close()

textname('紫川')
